### DISCUSSION TITLE
can I define icons for directories?

### DISCUSSION THREAD

**Discussion by pulumiup** [pls-rs/pls#121] [Help Q&A] [answered]
I have some specific directories in $HOME I was hoping I could define icons for those directories like you can file extension.

For example, I have a photos directory. I tried to do the following.

```yaml
icons:
   image: "<U+F4E5>" # nf-oct-image
specs:
  - pattern: photos$
    icons:
      - photo
```

I also tried ^photos$. I would expect it to match the directory photos and replace it with the icon. I have the icon specified in image, but when I pasted it I got the Unicode. The actual symbol is in my config though.

Thanks.
