### DISCUSSION TITLE
How to add a nerd-font icon

### DISCUSSION THREAD

**Discussion by bluelephant825** [pls-rs/pls#46] [Help Q&A] [answered]
I noticed that some document types, e.g. PDF, don't have an icon. I created a file called .pls.yml in my home directory ~ on my Mac containing the following code, but it's not working and I honestly don't understand how to validate my YAML file!

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/dhruvkb/pls/main/src/pls/data/schema/pls_config.yml

nerd_icons:
  pdf: "\uf724" # nf-mdi-file_pdf
```

Would be most grateful if someone could help me fix this!

**Comment by dhruvkb** [comment, marked as answer]
Hey @odebroqueville, there are two steps involved in adding an icon for a file type.

- icon mapping (the step that you have done)
- spec definition (the step that's missing)

Your `.pls.yml` file should look like this:

```yml
nerd_icons:
  pdf: "\uf724" # nf-mdi-file_pdf

node_specs: # teaches `pls` how to map files to icons and colors
  - extension: pdf
    icon: pdf
    color: "#ec1c24"
```
