### ISSUE TITLE
Custom icons are not rendered

### ISSUE THREAD

**Issue by vjousse** [pls-rs/pls#116]
## Description

When I use the config given in https://pls.cli.rs/guides/specs/

```yml
icons:
  javascript: "󰌞" # nf-md-language_javascript
  typescript: "󰛦" # nf-md-language_typescript
specs:
  - pattern: \.ts$
    icon: typescript
    style: rgb(49,120,198)
  - pattern: \.js$
    icon: javascript
    style: rgb(247,223,30)
    importance: -1
    collapse:
      ext: ts
  - pattern: prettier
    icon: broom
  - pattern: ^package\.json$
    icon: package
  - pattern: ^pnpm-lock\.yaml$
    icon: lock
    importance: -1
    collapse:
      name: package.json
  - pattern: ^(justfile|README.md)$
    style: green bold
    importance: 2
```

Here is what I see:

![241004_10-45-43](https://github.com/user-attachments/assets/0480b5c6-5eb0-4fa6-a5a4-d4d87d8e1981)

The screenshot of the config file edited with vim in the same Terminal (Kitty), icons are ok:

![241004_10-46-27](https://github.com/user-attachments/assets/db53ea77-6e8f-4805-a709-3a7e8dae6563)

## Expectations

Display the custom icon 󰛦  for `vite.config.ts`

## Environment

**`pls` specifications:**

- Version: `pls 0.0.1-beta.8`

Device specifications:

- Operating system: `Archlinux`
- Other info:
  - Term: `kitty`
  - Font: `FiraCode Nerd Font`
 
![241004_11-01-34](https://github.com/user-attachments/assets/d5d706c4-c54e-4feb-b6d5-f5ac437d28fe)

## Additional information

First: thanks for your work! And if there is anything else I can do to help debugging don't hesitate.
